# headers and icon 
title: Gibok Kim
info: DNQE22 @ KAIST
icon-pic: assets/img/nubjuki.jpg

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
